# Generated by Django 3.0.2 on 2020-04-22 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200421_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('whid', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='whid',
            field=models.IntegerField(default=1, verbose_name='get picked from'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='package',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='y',
            field=models.IntegerField(),
        ),
    ]
