# Generated by Django 3.0.2 on 2020-04-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200422_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
    ]
