# Generated by Django 3.0.2 on 2020-04-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200424_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='detail',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
