# Generated by Django 3.0.3 on 2020-04-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='X',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='Y',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='trackingNum',
            field=models.CharField(max_length=100),
        ),
    ]
