# Generated by Django 3.0.3 on 2020-04-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20200415_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Delivery Status (in warehouse, delivering, delivered)'),
        ),
    ]
