# Generated by Django 3.0.3 on 2020-04-15 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_delete_ownernsharer'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trackingNum', models.CharField(max_length=100)),
                ('X', models.CharField(max_length=100)),
                ('Y', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0, verbose_name='Delivery Status (in warehouse, delivering, delivered)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
