# Generated by Django 3.0.2 on 2020-04-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Y',
            new_name='y',
        ),
    ]
