# Generated by Django 3.0.2 on 2020-04-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200421_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='X',
            new_name='x',
        ),
    ]
