# Generated by Django 3.0.2 on 2020-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200422_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='owner name'),
        ),
        migrations.AlterField(
            model_name='package',
            name='whid',
            field=models.IntegerField(verbose_name='get picked from which wharehouse'),
        ),
    ]
