# Generated by Django 3.0.2 on 2020-04-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200423_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='package',
            name='whid',
        ),
        migrations.AddField(
            model_name='package',
            name='truckid',
            field=models.IntegerField(default=1, verbose_name='once carried by which truck'),
            preserve_default=False,
        ),
    ]
